feature: Improve Unix compatibility

diff --git a/bin/posix/git-delete b/bin/posix/git-delete
--- a/bin/posix/git-delete
+++ b/bin/posix/git-delete
@@ -14,11 +14,7 @@
 # work that is not merged elsewhere. Upstream branches are not deleted.
 # ==============================================================================
 
-# TODO: Move `repo_path` to external lib function.
-
 # Absolute path to this script, eg `/path/to/devtools/bin/posix/foo.sh`.
-# TODO: `readlink` is not a POSIX utility, so need to find a better cross-
-# platform way of achieving this.
 FILE_PATH=$(readlink -f "$0")
 
 # Absolute path to this script's parent directory, thus `/path/to/devtools/bin/posix`.
@@ -31,7 +27,7 @@ BIN_PATH=$(dirname "$DIR_PATH")
 REPO_PATH=$(dirname "$BIN_PATH")
 
 # Source ANSI code variables.
-source "${REPO_PATH}/lib/ansi-codes.sh"
+. "${REPO_PATH}/lib/ansi-codes.sh"
 
 # Was the target branch provided as a parameter?
 branch="${1}"
@@ -51,17 +47,17 @@ if [ -z "${branch}" ]; then
     branch_name="${branches[$i]}"
 
     # Remove refs/heads/ from start of branch name
-    echo -e "${YELLOW}${i}${RESET} - ${branch_name:11}"
+    printf "%s${i}%s - ${branch_name:11}" "${YELLOW}" "${RESET}"
   done
 
   echo ""
-  echo -e "${BLUE}Type the number of the branch you want to delete:${RESET}"
+  printf "%sType the number of the branch you want to delete:%s" "${BLUE}" "${RESET}"
 
   read -p "> " index
   echo ""
 
   if [ -z "${index}" ]; then
-    echo -e "${RED}Branch not provided, exiting...${RESET}" >&2
+    printf "%sBranch not provided, exiting...%s" "${RED}" "${RESET}" >&2
     exit 1
   fi
 
@@ -70,7 +66,7 @@ if [ -z "${branch}" ]; then
 
 fi
 
-echo -e "${GREEN}Attempting deletion of ${REVERSED} ${branch} ${RESET}"
+printf "%sAttempting deletion of %s ${branch} %s" "${GREEN}" "${REVERSED}" "${RESET}"
 
 # Attempt to delete the local branch. Silence non-error output and capture
 # errors. Respond to errors by asking the user if they want to try a force-delete.
@@ -80,7 +76,7 @@ EXIT_CODE_1=$?
 if [ ${EXIT_CODE_1} -eq 1 ]; then
 
   echo ""
-  echo -e "${RED}Branch deletion failed.${RESET}"
+  printf "%sBranch deletion failed.%s" "${RED}" "${RESET}"
   echo "Would you like to force deletion of this branch?"
   echo "WARNING: This is a destructive operation. This risks permanently losing commits that don't exist in the history of any other local branch."
   read -p "Force delete? (y/n) " choice
@@ -91,18 +87,18 @@ if [ ${EXIT_CODE_1} -eq 1 ]; then
       # branch almost certainly does not exist or is somehow protected from
       # deletion (for example, it is the current checked out branch).
       git branch --quiet --delete --force ${branch} 2> /dev/null
-      echo -e "${GREEN}Done.${RESET}"
+      printf "%sDone.%s" "${GREEN}" "${RESET}"
       ;;
 
     n|N )
-      echo -e "${RED}Exiting...${RESET}"
+      printf "%sExiting...%s" "${RED}" "${RESET}"
       ;;
 
     * )
-      echo -e "${RED}Exiting...${RESET}"
+      printf "%sExiting...%s" "${RED}" "${RESET}"
       ;;
   esac
 
 else
-  echo -e "${GREEN}Done.${RESET}"
+  printf "%sDone.%s" "${GREEN}" "${RESET}"
 fi
